### ISSUE TITLE
tensorboard needs to be installed separately

### ISSUE THREAD

**Issue by ankitapasad** [bshall/VectorQuantizedCPC#1]
I am using pytorch 1.5 and ran into the following issue with train_cpc.py

> ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above

The following solved the issue
```
pip install -U tb-nightly
```

**Comment by bshall** [comment]
Thanks @ankitapasad, 

I'll add tensorboard to the `requirements.txt`. I forgot that you need it installed even if you're just logging stuff.
