### ISSUE TITLE
Is there an easy way to do phonetic transcription with this model?

### ISSUE THREAD

**Issue by matthew-jurewicz** [bshall/VectorQuantizedCPC#4]

**Comment by bshall** [comment]
Hi @matthew-jurewicz,

The current model is completely unsupervised so you won't be able to transcribe phonemes directly. You can extract a sequence of acoustic units (i.e. code indices) but you'd have to do a bit more work to associate them with the correct phone. One simple thing to do is to train a network on top of the learned representation to predict the correct phoneme from ground truth alignments. Alternatively, more sophisticated approaches using CTC and fine-tuning would probably give the best results.

**Comment by matthew-jurewicz** [comment]
Assuming the code book represents phones, can't I generate audio for each code to figure out which phone it represents?

**Comment by bshall** [comment]
@matthew-jurewicz, that'd be very interesting to try, but I'm not sure if it'll work well. If you look at figure 3 in our [paper](https://arxiv.org/abs/2005.09409) you'll see that the codes aren't entirely consistent across a phoneme. So if you just pick a single code, repeat it for a few frames, and then synthesize, it's difficult to say what the result would be. If you have any success with that approach it'd be great to hear back.

Let me know if you have any other questions. Good luck!
